name: Call a reusable workflow

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      major_update:
        description: 'Set it to true to bump a major version'
        required: false
        default: false
        type: choice
        options: [true, false]

jobs:
  major-update:
    if: ${{ inputs.major_update == 'true' }}
    uses: ./.github/workflows/cd.yaml
    with:
      major_update: true
  minor-update:
    # check if on push
    if: ${{ inputs.major_update == '' }} || ${{ inputs.major_update == 'false' }}
    run:
      # echo input major update
      echo "major_update: ${{ inputs.major_update }}"
    uses: ./.github/workflows/cd.yaml
    with:
      major_update: false