name: Call a reusable workflow

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      major_update:
        description: 'Set it to true to bump a major version'
        required: false
        type: choice
        default: false

jobs:
  major-update:
    if: "${{ github.event.inputs.major_update == true }}"
    uses: ./.github/workflows/cd.yaml
    with:
      major_update: true
  minor-update:
    if: "${{ github.event.inputs.major_update == '' || github.event.inputs.major_update == false }}"
    uses: ./.github/workflows/cd.yaml
    with:
      major_update: false